categories:
- Data Managers
description: Index a FASTA file using the Burrows-Wheeler algorithm and populate the
  bwa_index.loc file.
long_description: ''
name: data_manager_bwa_index_builder
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/data_managers/data_manager_bwa_index_builder
type: unrestricted
