categories:
- Next Gen Mappers
description: 'Wrapper for bwa mem, aln, sampe, and samse'
long_description: |
  A collection of Galaxy bwa wrappers based on version 0.7.12.
name: bwa
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/bwa
type: unrestricted
