categories:
- Sequence Analysis
description: Contains tools for manipulating bamfiles.
long_description: |
  BAMTools is a collection of utilities for manipulating BAM files.
name: suite_bamtools_2_3_0
owner: devteam
homepage_url: https://github.com/pezmaster31/bamtools
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/suites/suite_bamtools_2_3_0
type: repository_suite_definition
