categories:
- Genomic Interval Operations
description: Intersect the intervals of two datasets
name: intersect
owner: devteam
homepage_url: https://github.com/galaxyproject/gops
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/gops/intersect
type: unrestricted
