categories:
- Sequence Analysis
- Variant Analysis
- Statistics
description: Perform Logistic Regression with vif
long_description: |
  This tool uses the ''glm'' function from R statistical package
  to perform logistic regression on the input data. It outputs one file containing
  the summary statistics of the performed regression. Also, it calculates VIF(Variance
  Inflation Factor) with ''vif'' function from library (car) in R.
name: logistic_regression_vif
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/logistic_regression_vif
type: unrestricted
