categories:
- Next Gen Mappers
- Sequence Analysis
description: Polymorphism of the Reads
long_description: |
  Calculate the percentage of reads supporting each nucleotide at
  each location
name: blat_coverage_report
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/blat_coverage_report
type: unrestricted
