categories:
- Sequence Analysis
- Variant Analysis
description: Fetch Indels from pairwise alignments
long_description: |
  This tool estimates the number of indels for every alignment block of the MAF file.
name: getindels_2way
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/getindels_2way
type: unrestricted
