language: python
python: 2.7
install:
  - pip install git+git://github.com/galaxyproject/planemo.git@master

script:
  - planemo shed_lint --report_level warn --tools --fail_level error --recursive .
