categories:
- Sequence Analysis
- Variant Analysis
description: Fetch substitutions from pairwise alignments
long_description: |
  This tool takes a pairwise MAF file as input and fetches substitutions per alignment block.
name: substitutions
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/substitutions
type: unrestricted
