homepage_url: https://www.broadinstitute.org/gatk/
categories:
- Variant Analysis
description: Variant Annotator
long_description: |
  Annotates variant calls with context information.  Users can specify
  which of the available annotations to use.
name: variant_annotator
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/gatk/variant_annotator
type: unrestricted
