categories:
- Sequence Analysis
description: Build custom track for UCSC genome browser
long_description: |
  This tool allows you to build custom tracks using datasets in your
  history for the UCSC genome browser. You can view these custom tracks on the UCSC
  genome browser by clicking on **display at UCSC main/test** link in the history
  panel of the output dataset.
name: ucsc_custom_track
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/main/tools/ucsc_custom_track
type: unrestricted
