categories:
 - Fasta Manipulation
description: Filter sequences by length
long_description: |
  Outputs sequences between Minimal length and Maximum length.
name: fasta_filter_by_length
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/fasta_filter_by_length
type: unrestricted
