owner: devteam
name: kraken
description: Contains a data manager that defines and populates the kraken_databases tool data table.
categories:
  - Metagenomics
long_description: 'Kraken is a system for assigning taxonomic labels to short DNA
  sequences, usually obtained through metagenomic studies. Previous attempts by other
  bioinformatics software to accomplish this task have often used sequence alignment
  or machine learning techniques that were quite slow, leading to the development of
  less sensitive but much faster abundance estimation programs. Kraken aims to achieve
  high sensitivity and high speed by utilizing exact alignments of k-mers and a novel
  classification algorithm.'
homepage_url: https://github.com/galaxyproject/tools-devteam/
remote_repository_url: https://github.com/galaxyproject/tools-devteam/blob/master/tool_collections/kraken/kraken/
