categories:
- Convert Formats
description: Tabular-to-FASTA
long_description: |
  Converts tab delimited data into FASTA formatted sequences.
name: tabular_to_fasta
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/tabular_to_fasta
type: unrestricted
