categories: []
description: RMAPQ for Solexa Short Reads Alignment with Quality Scores
long_description: |
  This tool runs rmapq, searching against a genome build with sequence qualities.
name: rmapq
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/rmapq
type: unrestricted
