categories:
- Genomic Interval Operations
description: Merge the overlapping intervals of a dataset
name: merge
owner: devteam
homepage_url: https://github.com/galaxyproject/gops
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/gops/merge
type: unrestricted
