owner: devteam
name: data_manager_fetch_ncbi_taxonomy
description: Contains a data manager that defines and populates the ncbi_taxonomy tool data table.
categories:
  - Data Managers
  - Metagenomics
long_description: 'Download the NCBI taxonomy files and add their paths to a data table'
homepage_url: https://github.com/galaxyproject/tools-devteam/
remote_repository_url: https://github.com/galaxyproject/tools-devteam/blob/master/data_managers/data_manager_fetch_ncbi_taxonomy/
