categories:
- ChIP-seq
description: Control-based ChIP-seq Analysis Tool
long_description: |
  This tool allows ChIP-seq peak/region calling using CCAT.
name: ccat
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/ccat
type: unrestricted
