categories:
- Variant Analysis
description: Merge multiple VCF datasets into a single dataset
name: vcftools_merge
owner: devteam
homepage_url: https://vcftools.github.io/
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/vcftools/vcftools_merge
type: unrestricted
