categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles the
  0.7.x version of bx-python.
long_description: |
  The bx-python project is a python library and associated set of
  scripts to allow for rapid implementation of genome scale analyses.
name: package_bx_python_0_7
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/packages/package_bx_python_0_7
type: tool_dependency_definition
homepage_url: https://bitbucket.org/james_taylor/bx-python
