homepage_url: https://www.broadinstitute.org/gatk/
categories:
- Variant Analysis
description: Unified Genotyper SNP and indel caller
long_description: |
  A variant caller which unifies the approaches of several disparate
  callers.  Works for single-sample and multi-sample data.  The user can choose from
  several different incorporated calculation models.
name: unified_genotyper
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/gatk/unified_genotyper
type: unrestricted
