categories:
- RNA
description: Tophat - fast splice junction mapper for RNA-Seq reads
homepage_url: http://ccb.jhu.edu/software/tophat/index.shtml
long_description: |
  TopHat is a fast splice junction mapper for RNA-Seq reads. It aligns
  RNA-Seq reads to mammalian-sized genomes using the ultra high-throughput short read
  aligner Bowtie(2), and then analyzes the mapping results to identify splice junctions
  between exons.
name: tophat2
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/tophat2
type: unrestricted
