homepage_url: https://github.com/galaxyproject/sequence_utils
categories:
- Fastq Manipulation
description: FASTQ Masker by quality score
long_description: |
  This tool allows masking base characters in FASTQ format files
  dependent upon user specified quality score value and comparison method.
name: fastq_masker_by_quality
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/galaxy_sequence_utils/fastq_masker_by_quality
type: unrestricted
