categories:
- Genomic Interval Operations
description: Fetch closest non-overlapping feature for every interval
long_description: |
  For every interval in the interval dataset, this tool fetches the
  closest non-overlapping upstream and / or downstream features from the features
  dataset.
name: flanking_features
owner: devteam
homepage_url: https://github.com/galaxyproject/gops
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/gops/flanking_features
type: unrestricted
