homepage_url: https://github.com/galaxyproject/sequence_utils
categories:
- Fastq Manipulation
description: FASTQ de-interlacer on paired end reads.
long_description: |
  De-interlaces a single fastq dataset representing paired-end run
  into two fastq datasets containing only the first or second mate read. Reads without
  mate are saved in separate output files.
name: fastq_paired_end_deinterlacer
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/galaxy_sequence_utils/fastq_paired_end_deinterlacer
type: unrestricted
