categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  3.0 of CCAT.
long_description: |
  CCAT is a software package for the analysis of ChIP-seq data with
  negative control.
name: package_ccat_3_0
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/packages/package_ccat_3_0
type: tool_dependency_definition
