categories:
- Metagenomics
description: A suite of Galaxy utilities associated with version 0.10.5 of the Kraken tool.
homepage_url: https://github.com/galaxyproject/tools-devteam/
long_description: |
  Kraken is a system for assigning taxonomic labels to short DNA
  sequences, usually obtained through metagenomic studies. Previous attempts by other
  bioinformatics software to accomplish this task have often used sequence alignment
  or machine learning techniques that were quite slow, leading to the development
  of less sensitive but much faster abundance estimation programs. Kraken aims to
  achieve high sensitivity and high speed by utilizing exact alignments of k-mers
  and a novel classification algorithm.
name: suite_kraken_0_10_5
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/blob/master/suites/suite_kraken_0_10_5/
type: repository_suite_definition
