categories:
- Graphics
- Visualization
description: HVIS visualization of genomic data with the Hilbert curve
long_description: |
  HilbertVis uses the Hilbert space-filling curve to visualize the
  structure of position-dependent data.  It maps the traditional one-dimensional line
  visualization onto a two-dimensional square.
name: hgv_hilbertvis
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/hgv/hgv_hilbertvis
type: unrestricted
