categories:
- Phylogenetics
- Sequence Analysis
description: ClustalW multiple sequence alignment program for DNA or proteins
long_description: |
  This tool allows you to run a multiple sequence alignment with
  ClustalW2 using the default options.
name: clustalw
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/clustalw
type: unrestricted
