categories:
- Genomic Interval Operations
description: Subtract the intervals of two datasets
name: subtract
owner: devteam
homepage_url: https://github.com/galaxyproject/gops
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/gops/subtract
type: unrestricted
