categories:
- Sequence Analysis
description: cufflinks gffread filters and/or converts GFF3/GTF2 records
long_description: |
  cufflinks gffread filters and/or converts GFF3/GTF2 records and
  can produce cdna, CDS, peptide fasta sequences
homepage_url: http://cole-trapnell-lab.github.io/cufflinks/
name: gffread
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/cufflinks/gffread
type: unrestricted
