categories:
- Sequence Analysis
- Variant Analysis
description: Extract orthologous microsatellites
long_description: |
  This tool finds ortholgous microsatellite blocks between aligned species.
name: multispecies_orthologous_microsats
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/multispecies_orthologous_microsats
type: unrestricted
