categories:
- Text Manipulation
description: Select lines from the end of a file.
long_description: |
  This tool outputs the specified number of lines from the end of the input dataset.
name: show_tail
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/show_tail
type: unrestricted
