categories:
- RNA
description: Filter Combined Transcripts
long_description: |
  Uses a tracking file (produced by cuffcompare) to filter a GTF
  file of transcripts (usually the transcripts produced by cufflinks). Filtering is
  done by extracting transcript IDs from tracking file and then filtering the GTF
  so that the output GTF contains only transcript found in the tracking file. Because
  a tracking file has multiple samples, a sample number is used to filter transcripts
  for a particular sample.
name: filter_transcripts_via_tracking
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/filter_transcripts_via_tracking
type: unrestricted
