categories:
- Tool Dependency Packages
description: Contains a tool dependency definition that downloads and compiles version
  1.7 of the the python numpy package
name: package_numpy_1_7
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/packages/package_numpy_1_7
type: tool_dependency_definition
