homepage_url: https://github.com/galaxyproject/sequence_utils
categories:
- Fastq Manipulation
description: FASTQ to FASTA converter
long_description: |
  This tool converts FASTQ sequencing reads to FASTA sequences.
name: fastqtofasta
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/galaxy_sequence_utils/fastqtofasta
type: unrestricted
