categories:
- Text Manipulation
description: Trim leading or trailing characters.
long_description: |
  Remove the specified number of characters from the beginning or
  end of each line or a single column in the input dataset.
name: trimmer
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/trimmer
type: unrestricted
