categories:
- RNA
description: Quantify the abundances of a set of target sequences from sampled subsequences
long_description: |
  eXpress is a streaming tool for quantifying the abundances of a
  set of target sequences from sampled subsequences. Example applications include
  transcript-level RNA-Seq quantification, allele-specific/haplotype expression analysis
  (from RNA-Seq), transcription factor binding quantification in ChIP-Seq, and analysis
  of metagenomic data. It is based on an online-EM algorithm [1] that results in space
  (memory) requirements proportional to the total size of the target sequences and
  time requirements that are proportional to the number of sampled fragments. Thus,
  in applications such as RNA-Seq, eXpress can accurately quantify much larger samples
  than other currently available tools greatly reducing computing infrastructure requirements.
  eXpress can be used to build lightweight high-throughput sequencing processing pipelines
  when coupled with a streaming aligner (such as Bowtie), as output can be piped directly
  into eXpress, effectively eliminating the need to store read alignments in memory
  or on disk.
name: express
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/express
type: unrestricted
