categories:
- Next Gen Mappers
description: Galaxy wrapper for the Lastz alignment tool on paired reads
long_description: |
  LASTZ is a program for aligning DNA sequences, a pairwise aligner.
  Originally designed to handle sequences the size of human chromosomes and from different
  species, it is also useful for sequences produced by NGS sequencing technologies
  such as Roche 454.
name: lastz_paired_reads
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/lastz_paired_reads
type: unrestricted
