categories:
- Variant Analysis
description: A suite of Galaxy utilities associated with version 14.08 of the vcflib.
long_description: |
  A simple C++ library for parsing and manipulating VCF files.
name: suite_vcflib_14_08
owner: devteam
homepage_url: https://github.com/ekg/vcflib
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/suites/suite_vcflib_14_08
type: repository_suite_definition
