categories:
- Data Managers
description: Builds sam indexes using the new data table format.
long_description: ''
name: data_manager_sam_fasta_index_builder
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/data_managers/data_manager_sam_fasta_index_builder
type: unrestricted
