homepage_url: https://www.broadinstitute.org/gatk/
categories:
- Variant Analysis
description: Eval Variants
long_description: |
  General-purpose tool for variant evaluation (% in dbSNP, genotype
  concordance, Ti/Tv ratios, and a lot more)
name: variant_eval
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/gatk/variant_eval
type: unrestricted
