categories:
- Variant Analysis
description: Extract reads from a specified region
long_description: |
  This tool uses vcfPytools'' extract command to extract reads from
  a specified region of a VCF file
name: vcf_extract
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/vcf_extract
type: unrestricted
