categories:
- Variant Analysis
description: Select samples from a VCF dataset
name: vcftools_subset
owner: devteam
homepage_url: https://vcftools.github.io/
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/vcftools/vcftools_subset
type: unrestricted
