categories:
- Text Manipulation
description: Merge columns together.
long_description: |
  This tool merges two or more columns from the input dataset into a single column.
name: merge_cols
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/merge_cols
type: unrestricted
