categories:
- Genomic Interval Operations
description: Complement intervals of a dataset
long_description: |
  This operation complements the regions of a set of intervals.  Regions
  are returned that represent the empty space in the input interval.
name: complement
owner: devteam
homepage_url: https://github.com/galaxyproject/gops
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/gops/complement
type: unrestricted
