categories:
- SAM
description: Filter pileup on coverage and SNPs
long_description: |
  Allows one to find sequence variants and/or sites covered by a
  specified number of reads with bases above a set quality threshold. The tool works
  on six and ten column pileup formats produced with *samtools pileup* command. However,
  it also allows you to specify columns in the input file manually.
name: pileup_parser
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/pileup_parser
type: unrestricted
