categories:
- Transcriptomics
description: Contains the full set of cuff* tools.
long_description: |
  Includes the following tools: cufflinks, cuffcompare, cuffmerge, cuffdiff, cuffnor, and cuffquant
name: all_cufflinks_tool_suite
owner: devteam
homepage_url: http://cole-trapnell-lab.github.io/cufflinks/
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/suites/all_cufflinks_tool_suite
type: repository_suite_definition
