categories:
- Variant Analysis
description: Intersect multiple VCF datasets
name: vcftools_isec
owner: devteam
homepage_url: https://vcftools.github.io/
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/vcftools/vcftools_isec
type: unrestricted
