categories:
- Sequence Analysis
description: Generate a Matrix for using PC and LDA
long_description: |
  This tool consists of a module to generate a matrix to be used
  for running the Linear Discriminant Analysis as described in Carrel et al., 2006
  (PMID: 17009873)
name: generate_pc_lda_matrix
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/generate_pc_lda_matrix
type: unrestricted
