categories:
- Text Manipulation
description: Select columns from a dataset.
long_description: |
  This tool selects specific columns from the input dataset.
name: cut_columns
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/cut_columns
type: unrestricted
