categories:
  - Metagenomics
description: Diversity Index via Vegan R package
long_description: |
  Gives the Diversity Index.

  http://cran.r-project.org/web/packages/vegan/index.html
name: vegan_diversity
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/vegan_diversity
