homepage_url: https://github.com/galaxyproject/sequence_utils
categories:
- Fastq Manipulation
description: Convert between various FASTQ quality formats.
long_description: |
  This tool offers several conversion options relating to the FASTQ format.
name: fastq_groomer
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/galaxy_sequence_utils/fastq_groomer
type: unrestricted
