categories:
- Genomic Interval Operations
description: Concatenate two bed files
name: concat
owner: devteam
homepage_url: https://github.com/galaxyproject/gops
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/gops/concat
type: unrestricted
