categories:
- Sequence Analysis
- Variant Analysis
description: Estimate Indel Rates for 3-way alignments
long_description: |
  This tool estimates the insertion and deletion rates for alignments
  in a window of specified size. Rates are computed over the total adjusted lengths
  (adjusted by disregarding masked bases) of all the alignments blocks from the indel
  file that fall within that window.
name: getindelrates_3way
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/getindelrates_3way
type: unrestricted
