categories:
- Text Manipulation
description: Select lines from the beginning of a file.
long_description: |
  This tool outputs the specified number of lines from the beginning of the input dataset.
name: show_beginning
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/show_beginning
type: unrestricted
