categories:
- Variant Analysis
description: Subset VCF dataset by genomic regions
name: vcftools_slice
owner: devteam
homepage_url: https://vcftools.github.io/
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/vcftools/vcftools_slice
type: unrestricted
