categories:
- Variant Analysis
description: 'Annotate a VCF file using ANNOVAR annotations to produce a tabular file that can be filtered'
long_description: |
  Please see the http://www.openbioinformatics.org/annovar/annovar_accessary.html#excel for details.
name: table_annovar
owner: devteam
remote_repository_url: Nonehttps://github.com/galaxyproject/tools-devteam/tree/master/tools/table_annovar
type: unrestricted
