categories:
- Genomic Interval Operations
description: Get flanks returns flanking region/s for every gene
long_description: |
  This tool finds the upstream and/or downstream flanking region(s)
  of all the selected regions in the input file.
name: get_flanks
owner: devteam
homepage_url: https://github.com/galaxyproject/gops
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/gops/get_flanks
type: unrestricted
