categories:
- ChIP-seq
description: Model-based Analysis of ChIP-Seq
long_description: |
  With the improvement of sequencing techniques, chromatin immunoprecipitation
  followed by high throughput sequencing (ChIP-Seq) is getting popular to study genome-wide
  protein-DNA interactions. To address the lack of powerful ChIP-Seq analysis method,
  we present a novel algorithm, named Model-based Analysis of ChIP-Seq (MACS), for
  identifying transcript factor binding sites. MACS captures the influence of genome
  complexity to evaluate the significance of enriched ChIP regions, and MACS improves
  the spatial resolution of binding sites through combining the information of both
  sequencing tag position and orientation. MACS can be easily used for ChIP-Seq data
  alone, or with control sample with the increase of specificity.
name: macs
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/macs
type: unrestricted
