categories:
- Fastq Manipulation
description: FASTQ Quality Trimmer by sliding window
long_description: |
  This tool allows you to trim the ends of reads based upon the aggregate
  value of quality scores found within a sliding window; a sliding window of size
  1 is equivalent to ''simple'' trimming of the ends.
name: fastq_trimmer_by_quality
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/fastq_trimmer_by_quality
type: unrestricted
