homepage_url: https://www.broadinstitute.org/gatk/
categories:
- Variant Analysis
description: Variant Filtration on VCF files
long_description: |
  Filters variant calls using a number of user-selectable, parameterizable criteria.
name: variant_filtration
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/gatk/variant_filtration
type: unrestricted
