categories:
- Genomic Interval Operations
description: Join the intervals of two datasets side-by-side
name: join
owner: devteam
homepage_url: https://github.com/galaxyproject/gops
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/gops/join
type: unrestricted
