categories:
- Statistics
description: Correlation for numeric columns
long_description: |
  This tool computes the matrix of correlation coefficients between
  numeric columns.
name: correlation
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/correlation
type: unrestricted
