categories:
- SAM
description: Filter SAM on bitwise flag values
long_description: |
  Allows parsing of SAM datasets using bitwise flag (the second column).
name: sam_bitwise_flag_filter
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/sam_bitwise_flag_filter
type: unrestricted
