homepage_url: https://github.com/galaxyproject/sequence_utils
categories:
- Fastq Manipulation
description: FASTQ to Tabular converter
long_description: |
  This tool converts FASTQ sequencing reads to a Tabular file.
name: fastq_to_tabular
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tool_collections/galaxy_sequence_utils/fastq_to_tabular
type: unrestricted
