categories:
- Data Managers
description: Retrieve a FASTA file and populate the all_fasta.loc data table.
long_description: ''
name: data_manager_fetch_genome_all_fasta
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/data_managers/data_manager_fetch_genome_all_fasta
type: unrestricted
