categories:
- Variant Analysis
description: Filter a VCF file
long_description: |
  This tool uses vcfPytools' filter command
name: vcf_filter
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/vcf_filter
type: unrestricted
