categories:
- Sequence Analysis
- Fasta Manipulation
description: Galaxy wrappers for Emboss version 5.0.0 tools
name: emboss_5
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/emboss_5
type: unrestricted
