categories: []
description: RMAP for Solexa Short Reads Alignment
long_description: |
  This tool runs rmap, mapping Solexa reads onto a genome build.
name: rmap
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/rmap
type: unrestricted
