categories:
- Statistics
description: Compute P-values and Second Moments for Feature Occurrences
long_description: |
  This program generates plots and computes table matrix of second
  moments, p-values, and test orientations at multiple scales for the correlation
  between the occurrences of features in one dataset and their occurrences in another
  using multiscale wavelet analysis technique.
name: dwt_ivc_all
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/dwt_ivc_all
type: unrestricted
