categories:
- Text Manipulation
description: Convert delimiters to tab.
long_description: |
  Convert all delimiters of the selected type into TAB characters.
name: convert_characters
owner: devteam
remote_repository_url: https://github.com/galaxyproject/tools-devteam/tree/master/tools/convert_characters
type: unrestricted
